version: "3.6"

services:
  money-transfer:
    deploy:
      replicas: 1
    build:
      context: ./
      dockerfile: Dockerfile-test
      args:
        - PINPOINT_VERSION=2.5.3
        - AGENT_ID=java-app-in-docker
        - APP_NAME=money-transfer
        - SPRING_PROFILES=local
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3307/money_transfer_service?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'password!'
    depends_on:
      - money-transfer-database

  money-transfer-database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: money_transfer_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'password!'
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--innodb_buffer_pool_size=512M"
